kind: pipeline
type: kubernetes
name: code-analysis

platform:
  os: linux
  arch: amd64

steps:
- name: ssh commands
  image: appleboy/drone-ssh
  settings:
    host: 52.221.47.110
    username: nhan
    password: nhan
    port: 22
    script:
      - whoami
      - echo world
 
 
 
